name: Build Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


permissions: 
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
        
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish to GitHub Pages (and render) 
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
